# redirect to ensure longer urls still fetch index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]

[context.lf-partner-preview.environment]
  REACT_APP_configUrlApi = "https://api.partner-platform.opentargets.org/api/v4/graphql"