# redirect to ensure longer urls still fetch index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  # REACT_APP_GTMID= "GTM-WPXWRDV"

[context.lf-partner-preview.environment]
  configUrlApi = "https://api.partner-platform.opentargets.org/api/v4/graphql"
  configUrlApiBeta = "https://api.partner-platform.opentargets.org/api/v4/graphql"
  REACT_APP_configPrimaryColor = "#407253"
