name: Workflow for Node using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    environment: SNYK_TOKEN
    steps:
      - uses: actions/checkout@dev
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
